dist: xenial
language: minimal
addons:
  apt:
    packages:
    - qemu
    - gdisk
    - dosfstools
    - e2fsprogs
    - pixz
    - debootstrap
env:
  matrix:
    - RELEASE="trusty"
    - RELEASE="xenial"
    - RELEASE="bionic"
script:
  - sudo ./vagrant-box-libvirt-ubuntu
