dist: xenial
language: minimal
addons:
  apt:
    packages:
    - qemu
    - gdisk
    - dosfstools
    - e2fsprogs
    - pixz
    - debootstrap
env:
  global:
    - MIRROR_UBUNTU="http://us-east-1.ec2.archive.ubuntu.com/ubuntu"
  matrix:
    - RELEASE="trusty"
    - RELEASE="xenial"
    - RELEASE="bionic"
script:
  - sudo ./vagrant-box-libvirt-ubuntu
