name: CI
on:
  workflow_dispatch:
  push:
    branches:
    - 'master'
    tags:
    - 'v*'
permissions:
  contents: read
jobs:
  ci:
    strategy:
      matrix:
        release: [jammy, focal, bionic]
    timeout-minutes: 15
    name: CI
    runs-on: ubuntu-latest
    steps:
    ################################################################################
    # Checkout
    ################################################################################
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ startsWith(github.ref, 'refs/tags/') && '0' || '1' }}
    ################################################################################
    # Required Packages
    ################################################################################
    - name: Required Packages
      run: |
        sudo apt-get update
        sudo apt-get install -qq qemu-utils gdisk dosfstools e2fsprogs xfsprogs pixz debootstrap
    ################################################################################
    # Build Vagrant Box
    ################################################################################
    - name: Build Vagrant Box
      run: sudo -E bash -x vagrant-box-libvirt-ubuntu
      env:
        WORK_DIR: /opt/rootfs
        RELEASE: ${{ matrix.release }}
